CREATE TABLE "pg-drizzle_reaction" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_reaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"postId" integer NOT NULL,
	"emoji" text NOT NULL,
	"createdBy" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_room_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_room_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"roomId" text NOT NULL,
	"youtubeUrl" text NOT NULL,
	"videoId" text NOT NULL,
	"startTime" integer NOT NULL,
	"endTime" integer NOT NULL,
	"description" text,
	"createdBy" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_room" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"createdBy" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_reaction" ADD CONSTRAINT "pg-drizzle_reaction_postId_pg-drizzle_room_post_id_fk" FOREIGN KEY ("postId") REFERENCES "public"."pg-drizzle_room_post"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "pg-drizzle_room_post" ADD CONSTRAINT "pg-drizzle_room_post_roomId_pg-drizzle_room_id_fk" FOREIGN KEY ("roomId") REFERENCES "public"."pg-drizzle_room"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "reaction_post_idx" ON "pg-drizzle_reaction" USING btree ("postId");
--> statement-breakpoint
CREATE INDEX "reaction_created_by_idx" ON "pg-drizzle_reaction" USING btree ("createdBy");
--> statement-breakpoint
CREATE INDEX "room_post_room_idx" ON "pg-drizzle_room_post" USING btree ("roomId");
